import { useEffect } from "react";
import { useNavigate, useParams } from "react-router-dom";

import { useToast } from "../components/ToastProvider";
import ThumbnailGrid from "../components/ThumbnailGrid";
import { useDeleteVideo } from "../hooks/useDeleteVideo";
import { useGenerateThumbnails } from "../hooks/useGenerateThumbnails";
import { useSelectThumbnail } from "../hooks/useSelectThumbnail";
import { useVideoDetail } from "../hooks/useVideoDetail";
import { resolveAssetUrl } from "../utils/assetUrl";
import { formatDate } from "../utils/formatters";

const autoGeneratedThumbnailVideoIds = new Set();

function VideoDetailPage() {
  const { id } = useParams();
  const navigate = useNavigate();
  const { data: video, isLoading, isError, error } = useVideoDetail(id);
  const deleteMutation = useDeleteVideo();
  const generateMutation = useGenerateThumbnails(id);
  const selectMutation = useSelectThumbnail(id);
  const { error: showErrorToast, success } = useToast();
  const posterUrl = resolveAssetUrl(
    video?.primaryThumbnail?.url || video?.primaryThumbnail?.thumbnailUrl
  );

  const hasThumbnails = Boolean(video?.thumbnails && video.thumbnails.length > 0);

  useEffect(() => {
    if (!id || isLoading || isError || !video || hasThumbnails) {
      return;
    }

    if (autoGeneratedThumbnailVideoIds.has(id)) {
      return;
    }

    autoGeneratedThumbnailVideoIds.add(id);
    generateMutation.mutate(id);
  }, [generateMutation, hasThumbnails, id, isError, isLoading, video]);

  if (isLoading) {
    return <p className="text-sm text-slate-500">Loading video...</p>;
  }

  if (isError) {
    return <p className="text-sm text-red-600">{error.message}</p>;
  }

  const handleDelete = async () => {
    const didConfirm = window.confirm(
      `Delete "${video.title || "this video"}" and all generated thumbnails?`
    );

    if (!didConfirm) {
      return;
    }

    try {
      await deleteMutation.mutateAsync(id);
      success("Video deleted", `"${video.title || "Your video"}" was removed successfully.`);
      navigate("/");
    } catch (error) {
      showErrorToast(
        "Delete failed",
        error.response?.data?.message || error.message || "Unable to delete the video."
      );
    }
  };

  return (
    <div className="space-y-8">
      <section className="grid gap-8 lg:grid-cols-[1.3fr_0.7fr]">
        <div className="overflow-hidden rounded-[2rem] border border-white/70 bg-black shadow-[0_30px_80px_rgba(15,23,42,0.18)]">
          <video
            src={video.videoUrl}
            poster={posterUrl || undefined}
            controls
            className="aspect-video h-full w-full"
          />
        </div>

        <aside className="space-y-6 rounded-[2rem] border border-white/70 bg-white/90 p-6 shadow-[0_20px_60px_rgba(148,163,184,0.18)]">
          <div>
            <p className="text-sm font-semibold uppercase tracking-[0.2em] text-brand-500">
              Video details
            </p>
            <h1 className="mt-2 text-3xl font-semibold tracking-tight text-slate-900">
              {video.title || "Untitled video"}
            </h1>
            <p className="mt-2 text-sm text-slate-500">Uploaded {formatDate(video.createdAt)}</p>
          </div>

          <p className="text-sm leading-7 text-slate-600">
            {video.description || "No description provided."}
          </p>

          <div className="grid gap-3 sm:grid-cols-2">
            <div className="rounded-2xl bg-slate-50 px-4 py-4">
              <p className="text-xs font-semibold uppercase tracking-[0.22em] text-slate-500">
                Thumbnail count
              </p>
              <p className="mt-2 text-2xl font-semibold text-slate-950">
                {video.thumbnails?.length || 0}
              </p>
            </div>
            <div className="rounded-2xl bg-slate-50 px-4 py-4">
              <p className="text-xs font-semibold uppercase tracking-[0.22em] text-slate-500">
                Primary status
              </p>
              <p className="mt-2 text-2xl font-semibold text-slate-950">
                {video.primaryThumbnail ? "Selected" : "Pending"}
              </p>
            </div>
          </div>

          <div className="flex flex-wrap gap-2">
            {Array.isArray(video.tags) && video.tags.length ? (
              video.tags.map((tag) => (
                <span
                  key={tag}
                  className="rounded-full bg-slate-100 px-3 py-1 text-xs font-medium text-slate-600"
                >
                  #{tag}
                </span>
              ))
            ) : (
              <span className="text-sm text-slate-500">No tags</span>
            )}
          </div>

          <div className="flex flex-wrap gap-3">
            <button
              type="button"
              onClick={() => generateMutation.mutate()}
              disabled={generateMutation.isPending || deleteMutation.isPending}
              className="inline-flex rounded-full border border-slate-300 px-5 py-2.5 text-sm font-semibold text-slate-700 transition hover:border-brand-500 hover:text-brand-500 disabled:cursor-not-allowed disabled:opacity-60"
            >
              {generateMutation.isPending ? "Generating..." : "Regenerate thumbnails"}
            </button>

            <button
              type="button"
              onClick={handleDelete}
              disabled={deleteMutation.isPending || generateMutation.isPending}
              className="inline-flex rounded-full border border-red-200 px-5 py-2.5 text-sm font-semibold text-red-600 transition hover:border-red-500 hover:bg-red-50 disabled:cursor-not-allowed disabled:opacity-60"
            >
              {deleteMutation.isPending ? "Deleting..." : "Delete video"}
            </button>
          </div>

          {deleteMutation.isError ? (
            <p className="text-sm text-red-600">
              {deleteMutation.error.response?.data?.message || deleteMutation.error.message}
            </p>
          ) : null}
        </aside>
      </section>

      <section className="space-y-4">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-2xl font-semibold text-slate-900">Thumbnails</h2>
            <p className="text-sm text-slate-500">
              Click any frame to mark it as the primary thumbnail.
            </p>
          </div>
        </div>

        <ThumbnailGrid
          thumbnails={video.thumbnails}
          primaryThumbnailId={video.primaryThumbnail?._id || ""}
          isSelectable
          isLoading={selectMutation.isPending}
          onSelect={async (thumbnailId) => {
            try {
              await selectMutation.mutateAsync(thumbnailId);
              success("Thumbnail updated", "The primary thumbnail was changed successfully.");
            } catch (error) {
              showErrorToast(
                "Thumbnail update failed",
                error.response?.data?.message || error.message || "Unable to update the thumbnail."
              );
            }
          }}
        />

        {selectMutation.isError ? (
          <p className="text-sm text-red-600">
            {selectMutation.error.response?.data?.message || selectMutation.error.message}
          </p>
        ) : null}
      </section>
    </div>
  );
}

export default VideoDetailPage;
